import pytest
from typing import List, Any, Dict

from app.interfaces import (
    registry,
    ReceiptItem,
    ReceiptData,
    SavedReceiptResult,
    DuplicateAlert,
    PurchaseMatch,
    DealAlert,
    RedactionResult,
    ReceiptParser,
    PurchaseMemoryRepository,
    DealsClient,
    SecurityRedactor,
    AgentRunLogger
)
from app.agent import (
    preprocess_input,
    receipt_agent,
    memory_engine,
    deals_engine,
    query_purchase_history,
    MemoryAgentOutput
)


# --- Define Mock/Fake Classes to prove each interface can be implemented ---

class MockReceiptParser:
    def parse(self, input_text: str) -> ReceiptData:
        return ReceiptData(
            store="Mock Store",
            date="2026-07-01",
            items=[ReceiptItem(name="Mock Item", price=5.0)],
            prices=[5.0],
            total=5.0
        )

class MockMemoryRepository:
    def __init__(self):
        self.saved = []
    def save_receipt(self, receipt: ReceiptData, household_id: str = "default") -> SavedReceiptResult:
        self.saved.append(receipt)
        return SavedReceiptResult(receipt_id=100, success=True)
    def find_duplicates(self, items: List[ReceiptItem], store: str, date: str, household_id: str) -> List[DuplicateAlert]:
        return [DuplicateAlert(message="Mock duplicate found")]
    def query_purchase_history(self, query: str, household_id: str) -> List[PurchaseMatch]:
        return [PurchaseMatch(store="Mock Store", date="2026-07-01", item_name=query, price=5.0)]

class MockDealsClient:
    def lookup_price(self, product_name: str) -> List[DealAlert]:
        return []
    def check_price_drop(self, product_name: str, paid_price: float) -> List[DealAlert]:
        return [
            DealAlert(
                item_name=product_name,
                current_price=paid_price,
                deal_price=paid_price - 1.0,
                store="Mock Deal Store",
                details="Mock price drop details"
            )
        ]

class MockSecurityRedactor:
    def mask_pii(self, text: str) -> RedactionResult:
        return RedactionResult(sanitized_text="Redacted Text", redacted_items_count=1)

class MockAgentRunLogger:
    def __init__(self):
        self.logs = []
    def log_input(self, step: str, input_data: Any) -> None:
        self.logs.append(f"input:{step}")
    def log_tool_call(self, step: str, tool_name: str, args: Any) -> None:
        self.logs.append(f"tool:{step}:{tool_name}")
    def log_output(self, step: str, output_data: Any) -> None:
        self.logs.append(f"output:{step}")
    def log_error(self, step: str, error_message: str) -> None:
        self.logs.append(f"error:{step}")


# --- Unit Tests verifying each interface can be mocked ---

def test_interfaces_conformance():
    """Verify that mock implementations conform to typing.Protocol interfaces."""
    parser: ReceiptParser = MockReceiptParser()
    repo: PurchaseMemoryRepository = MockMemoryRepository()
    deals: DealsClient = MockDealsClient()
    redactor: SecurityRedactor = MockSecurityRedactor()
    logger: AgentRunLogger = MockAgentRunLogger()

    assert parser.parse("text").store == "Mock Store"
    assert repo.save_receipt(None).success is True
    assert len(deals.check_price_drop("item", 10.0)) == 1
    assert redactor.mask_pii("text").sanitized_text == "Redacted Text"
    
    logger.log_input("step", {})
    assert len(logger.logs) == 1


# --- Test showing DealsClient can be swapped with a fake in the workflow ---

def test_deals_client_swappable():
    """Verify the workflow node uses the swapped DealsClient."""
    original_client = registry.deals_client
    fake_client = MockDealsClient()
    registry.deals_client = fake_client

    try:
        input_data = MemoryAgentOutput(
            receipt=ReceiptData(
                store="Safeway",
                date="2026-07-01",
                items=[ReceiptItem(name="Apples", price=4.0)],
                prices=[4.0],
                total=4.0
            ),
            is_duplicate_receipt=False,
            duplicate_items=[]
        )
        
        # Execute the deals engine node directly
        output = deals_engine(input_data)
        
        # Assert that it matched the deal generated by our MockDealsClient
        assert len(output.deals) == 1
        assert output.deals[0].store == "Mock Deal Store"
        assert output.deals[0].deal_price == 3.0
    finally:
        # Restore original client
        registry.deals_client = original_client


# --- Test showing PurchaseMemoryRepository can be swapped with a fake in the workflow ---

def test_memory_repo_swappable():
    """Verify the workflow nodes use the swapped PurchaseMemoryRepository."""
    original_repo = registry.memory_repo
    fake_repo = MockMemoryRepository()
    registry.memory_repo = fake_repo

    try:
        # 1. Test memory_engine_node saving and duplicates
        input_receipt = ReceiptData(
            store="Trader Joe's",
            date="2026-07-01",
            items=[ReceiptItem(name="Butteries", price=10.0)],
            prices=[10.0],
            total=10.0
        )
        
        output = memory_engine(input_receipt)
        
        # Assert duplicate check warning was resolved via MockMemoryRepository
        assert len(output.duplicate_items) == 1
        assert output.duplicate_items[0] == "Mock duplicate found"
        
        # Assert the receipt was saved to our fake repository
        assert len(fake_repo.saved) == 1
        assert fake_repo.saved[0].store == "Trader Joe's"

        # 2. Test query_purchase_history tool calls fake repository search
        tool_output = query_purchase_history("Butteries")
        results = tool_output.get("results", [])
        assert len(results) == 1
        assert results[0]["store"] == "Mock Store"
        assert results[0]["item_name"] == "Butteries"
        assert results[0]["price"] == 5.0
    finally:
        # Restore original repository
        registry.memory_repo = original_repo
